services:
  minio:
    image: minio/minio
    container_name: minio
    command: server --address "0.0.0.0:9000" --console-address "0.0.0.0:9001" /data
    restart: always
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
      - MINIO_DOMAIN=minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    networks:
      shared_network:
        aliases:
          - ${LAKEHOUSE_NAME}.minio
  mc:
    image: minio/mc
    container_name: mc
    hostname: mc
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    entrypoint: >-
      /bin/sh -c "
 
      until (/usr/bin/mc config host add minio ${S3_ENDPOINT}
      ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY}) do echo ...waiting... &&
      sleep 1; done;
 
      /usr/bin/mc mb minio/${LAKEHOUSE_NAME};
 
      /usr/bin/mc policy set public minio/${LAKEHOUSE_NAME};
 
      tail -f /dev/null;
 
      "
    networks:
      - shared_network
    depends_on:
      - minio
volumes:
  minio_data: null
networks:
  shared_network:
    driver: bridge